python inspect_model.py \
    --log_msg base_decay_embedding \
    --log_dir /media/storage0/pwchi/Graph_Laplacian_Transformer \
    --dataset_dir /media/data/pwchi/Graph_Laplacian_Transformer \
    --dataset_name ogbg-molhiv \
    --num_workers 2 \
    --cuda_device 1 \
    --epoch 50 \
    --batch_size 32 \
    --lr 0.001 \
    --num_token_layer 8 \
    --num_cls_layer 2 \
    --dim 128 \
    --heads 4 \
    --head_expand_scale 2 \
    --alpha 0.0001 \
    --ff_dropout 0.1 \
    --attention_dropout 0.1 \
    --path_dropout 0.1 \
    --min_lr 0.000001 \
    --grad_clip_value 1e-1 \
    --num_classes 1 \
    --use_bias \
    --use_edge_bias \
    --use_attn_expand_bias \
    --checkpoint_folder run_2021-07-14-17-47-48_base_decay_embedding \
    --checkpoint_name checkpoint_2021-07-14-17-47-48_0_1028.pt \

python inspect_model.py \
    --log_msg base_decay_embedding \
    --log_dir /media/storage0/pwchi/Graph_Laplacian_Transformer \
    --dataset_dir /media/data/pwchi/Graph_Laplacian_Transformer \
    --dataset_name ogbg-molhiv \
    --num_workers 2 \
    --cuda_device 1 \
    --epoch 50 \
    --batch_size 32 \
    --lr 0.001 \
    --num_token_layer 8 \
    --num_cls_layer 2 \
    --dim 128 \
    --heads 4 \
    --head_expand_scale 2 \
    --alpha 0.0001 \
    --ff_dropout 0.1 \
    --attention_dropout 0.1 \
    --path_dropout 0.1 \
    --min_lr 0.000001 \
    --grad_clip_value 1e-1 \
    --num_classes 1 \
    --use_bias \
    --use_edge_bias \
    --use_attn_expand_bias \
    --checkpoint_folder run_2021-07-15-23-35-31_base_no_layer_scale_no_lap_add_emb_proj_no_path_drop_no_attn_drop \
    --checkpoint_name checkpoint_2021-07-15-23-35-31_40_42188.pt \